---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket=/var/run/containerd/containerd.sock"
  register: reset_cluster
  become: yes

- name: Copy deployment file
  ansible.builtin.copy:
    src: ./nginx.yml
    dest: nginx.yml
    mode: '0644'

- name: initialize the cluster
  when: reset_cluster is succeeded
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version stable-1.20 
                      #--apiserver-advertise-address {{ ansible_host }}
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copies admin.conf to users kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: install Pod network
  become: yes
  become_user: ubuntu
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    chdir: $HOME
        
- name: Get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: set join command
  set_fact:
    join_command: "{{ kubernetes_join_command.stdout_lines[0] }}"

#- name: start LB
#  become: yes
#  become_user: ubuntu
#  shell: kubectl apply -f ...
#  args:
#    chdir: $HOME

- name: start nginx
  become: yes
  become_user: ubuntu
  shell: kubectl apply -f $HOME/nginx.yml
  args:
    chdir: $HOME
